hold:
#  1:
#    sendkey: "LEFTCTRL+LEFTSHIFT+TAB"
#  2:
#    sendkey: "LEFTCTRL+TAB"
  3:
    sendkey: "LEFTALT+LEFT"
  4:
    sendkey: "LEFTALT+RIGHT"
pinch:
  3:
    out:
      sendkey: "LEFTCTRL+TAB"  
    in: 
      sendkey: "LEFTCTRL+LEFTSHIFT+TAB"  
# rotate:
#   2: 
#     clockwise: 
#       sendkey: "LEFTCTRL+TAB"
#     counterclockwise: 
#       sendkey: "LEFTCTRL+LEFTSHIFT+TAB"
threshold: 
  swipe: 0.5555
  hold: 0.5
  pinch: 0.2
  rotate: 0.4
  
