preload = ~/Pictures/Wallpapers/favourites/green-mountains.jpeg
wallpaper = eDP-1,~/Pictures/Wallpapers/favourites/green-mountains.jpeg
wallpaper = eDP-2,~/Pictures/Wallpapers/favourites/green-mountains.jpeg
