add_newline = true

format = """
[| $username](green)$directory$python$package$conda$git_status$git_branch
[  ➜  ](green) """

right_format = "$time$character$status"

[character]
success_symbol = "[<](bold green)"
error_symbol = "[<](bold red)"
vimcmd_symbol = "[CMD](bold white)"

[status]
format = "[$symbol $status]($style)"
disabled = false

[username]
show_always = true
style_user = "blue"

[c]
symbol = " "

[conda]
symbol = " "
format = "[$symbol$environment](blue)"
ignore_base = false

[directory]
truncation_length = 5
truncation_symbol = '.../'

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
style = "yellow"

[time]
format = "[$time](white)"
time_format = "%T, %v "
disabled = false
utc_time_offset = "+2"

