add_newline = true

format = """
[| $username](green)$directory$package$conda$git_status$git_branch$status
[  ➜  ](green) """

[status]
disabled = false

[username]
show_always = true
style_user = "blue"

[c]
symbol = " "

[conda]
symbol = " "
format = "[$symbol$environment](blue)"
ignore_base = false

[directory]
read_only = " "

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
style = "yellow"
